name: Main Flutter Release
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  make-release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version
        id: get-version
        #run: echo "version=$(grep -o -m 1  "[0-9]\+\.[0-9]\+\.[0-9]\+" pubspec.yaml)" >> $GITHUB_OUTPUT
        run: |
            VERSION=$(grep -o "grep -o -m 1  "[0-9]\+\.[0-9]\+\.[0-9]\+" pubspec.yaml)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Found version: $VERSION"

      #- name: Create Tag
      #  run: bash ./scripts/tag-and-release.sh tag ${{ secrets.GITHUB_TOKEN }} ${{ steps.get-version.outputs.version }}
